#!/usr/bin/env node
/**
 * Render the generated reference pages from the pinned inputs in
 * scripts/reference/sources (zero dependencies, no network).
 *
 *   node scripts/reference/generate.mjs           write pages + the Reference tab in docs.json
 *   node scripts/reference/generate.mjs --check   fail if anything on disk differs (CI)
 *
 * Pages:
 *   mcp/tools-reference, mcp/tools/*        Summer Engine MCP tools
 *   api-reference/http/**                  Summer Platform HTTP API (Mintlify OpenAPI pages)
 *   api-reference/gdscript/**              In-game Summer GDScript API
 *   api-reference/overview                 the Reference landing page
 *
 * To refresh the inputs from their sources, run scripts/reference/sync.mjs.
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { findPublicTextViolation } from "./lib/redact.mjs";
import { code, fm } from "./lib/mdx.mjs";
import { MCP_GROUPS, mcpEntries, mcpGroupPath, renderMcpGroupPage, renderMcpIndexPage } from "./render-mcp.mjs";
import { HTTP_BASE, httpNav, httpOperations, renderHttpOperationPage, renderHttpOverview } from "./render-http.mjs";
import { GD_BASE, gdPages, renderGdClassPage, renderGdOverviewExtras } from "./render-gdscript.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const SOURCES = join(HERE, "sources");
const CHECK = process.argv.includes("--check");
const OWNED_DIRS = ["mcp/tools", HTTP_BASE, GD_BASE];
const OWNED_GROUPS = ["Overview", "MCP tools", "HTTP API", "GDScript API"];
const LANDING = "api-reference/overview";

const readJson = (p) => JSON.parse(readFileSync(p, "utf8"));

// ------------------------------------------------------------------ render

const pages = new Map();
const put = (path, content) => pages.set(`${path}.mdx`, content.endsWith("\n") ? content : content + "\n");

// MCP
const mcpSrc = readJson(join(SOURCES, "mcp-tools.json"));
const entries = mcpEntries(mcpSrc);
put("mcp/tools-reference", renderMcpIndexPage(entries, mcpSrc));
for (const g of MCP_GROUPS) put(mcpGroupPath(g.id), renderMcpGroupPage(g, entries, mcpSrc));

// HTTP
const httpManifest = readJson(join(SOURCES, "http-api.json"));
const specs = Object.fromEntries(httpManifest.apis.map((a) => [a.id, readJson(join(SOURCES, "openapi", `${a.id}.json`))]));
const ops = httpOperations(httpManifest, specs);
put(`${HTTP_BASE}/overview`, renderHttpOverview(httpManifest, ops));
for (const o of ops) put(o.page, renderHttpOperationPage(o));

// GDScript
const gdSrc = readJson(join(SOURCES, "gdscript-api.json"));
const gp = gdPages(gdSrc);
for (const [cls, p] of gp) {
  let body = renderGdClassPage(cls, gdSrc, gp);
  if (cls === "SummerRuntime") {
    body = body
      .replace(/^title: .*$/m, `title: ${fm("In-game Summer API (GDScript)")}`)
      .replace(/^description: .*$/m, `description: ${fm("The Summer singleton your game code calls: Summer.client for the player's game (analytics, store, friends, party, chat, matchmaking, leaderboards, player data) and Summer.authority for your server (match results, world saves, ratings). Generated from the engine's class reference.")}`)
      .replace(/^generated: true$/m, `sidebarTitle: "Overview"\nicon: "code"\ngenerated: true`);
    body = body.trimEnd() + "\n\n" + renderGdOverviewExtras(gdSrc, gp);
  }
  put(p.path, body);
}

// Landing page
put(
  LANDING,
  [
    "---",
    'title: "Technical reference"',
    'sidebarTitle: "Overview"',
    `description: ${fm("Generated reference for Summer: every MCP tool, the public Summer Platform HTTP API and the in-game Summer GDScript API. Built from the source code, never written by hand.")}`,
    'icon: "book-marked"',
    "generated: true",
    "generator: scripts/reference",
    "---",
    "",
    "{/* Generated by scripts/reference/generate.mjs. Do not edit by hand. */}",
    "",
    "The guides explain how to make and ship a game. This reference lists every tool, endpoint and method, with exact names and inputs. It is generated from Summer's source code, and a docs check fails when a page no longer matches its source.",
    "",
    "<CardGroup cols={3}>",
    `  <Card title="MCP tools" icon="wrench" href="/mcp/tools-reference">`,
    `    ${entries.length} tools your agent can call: build, create assets, run and test, publish, grow.`,
    "  </Card>",
    `  <Card title="HTTP API" icon="globe" href="/${HTTP_BASE}/overview">`,
    `    ${ops.length} operations on ${httpManifest.server.replace(/^https:\/\//, "")}: creator management, analytics, store and account.`,
    "  </Card>",
    `  <Card title="GDScript API" icon="code" href="/${GD_BASE}/overview">`,
    `    The ${code("Summer")} singleton: ${code("Summer.client")} in the player's game, ${code("Summer.authority")} on your server.`,
    "  </Card>",
    "</CardGroup>",
    "",
    "## Where each page comes from",
    "",
    "| Reference | Source of truth | Version |",
    "|---|---|---|",
    `| MCP tools (local) | ${code("summer-engine")} npm package: its MCP server's tool list, ${code("library/tools/*/resource.yaml")}, ${code("registry/generated/index.json")} | ${code(mcpSrc.sources.local.version)} |`,
    `| MCP tools (hosted) | Hosted Summer Engine MCP, ${code("src/lib/mcp/hosted")} in publicsummerengine | ${code(mcpSrc.sources.hosted.commit.slice(0, 10))} |`,
    `| HTTP API | ${httpManifest.apis.map((a) => code(a.spec)).join(", ")} in summer-platform | ${code(httpManifest.commit.slice(0, 10))} |`,
    `| GDScript API | ${gdSrc.paths.map(code).join(", ")} in SummerEngine | ${code(gdSrc.commit.slice(0, 10))} |`,
    "",
    "Agents can read all of it at [llms.txt](https://docs.summerengine.com/llms.txt) and [llms-full.txt](https://docs.summerengine.com/llms-full.txt).",
    "",
  ].join("\n"),
);

// ------------------------------------------------------------- navigation

function gdNav() {
  const byKind = (kind) => [...gp.values()].filter((p) => p.kind === kind).map((p) => p.path);
  return {
    group: "GDScript API",
    pages: [
      `${GD_BASE}/overview`,
      `${GD_BASE}/client`,
      { group: "Summer.client", pages: byKind("client") },
      `${GD_BASE}/authority`,
      { group: "Summer.authority", pages: byKind("authority") },
      ...(gp.has("SummerMultiplayerService") ? [`${GD_BASE}/multiplayer`] : []),
      { group: "Types", pages: byKind("type") },
    ],
  };
}

function referenceGroups() {
  return [
    { group: "Overview", pages: [LANDING, "reference/compatibility"] },
    { group: "MCP tools", pages: ["mcp/tools-reference", ...MCP_GROUPS.map((g) => mcpGroupPath(g.id))] },
    { group: "HTTP API", pages: [`${HTTP_BASE}/overview`, ...httpNav(httpManifest, ops)] },
    gdNav(),
  ];
}

const docsJsonPath = join(ROOT, "docs.json");
const docsJsonRaw = readFileSync(docsJsonPath, "utf8");
const docs = JSON.parse(docsJsonRaw);
const refTab = docs.navigation.tabs.find((t) => t.tab === "Reference");
if (!refTab) throw new Error("docs.json has no Reference tab");
refTab.groups = [...referenceGroups(), ...refTab.groups.filter((g) => !OWNED_GROUPS.includes(g.group) && g.group !== "Reference")];
const docsJsonNext = JSON.stringify(docs, null, 2) + "\n";

// ------------------------------------------------------------- write/check

function listOwned() {
  const out = [];
  const walk = (dir) => {
    if (!existsSync(dir)) return;
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith(".mdx")) out.push(relative(ROOT, p).split(sep).join("/"));
    }
  };
  OWNED_DIRS.forEach((d) => walk(join(ROOT, d)));
  return out;
}

const problems = [];
for (const [path, content] of pages) {
  const v = findPublicTextViolation(content);
  if (v) problems.push(`${path}: public text guard (prices): …${v}…`);
}
for (const f of readdirSync(join(SOURCES, "openapi"))) {
  const raw = readFileSync(join(SOURCES, "openapi", f), "utf8");
  for (const host of [/example\.invalid/, /\.internal\b(?!\))/, /\.ts\.net/, /cluster\.local/, /api\.staging\./]) {
    if (host.test(raw)) problems.push(`scripts/reference/sources/openapi/${f}: internal host ${host}`);
  }
}

const stale = [];
for (const [path, content] of pages) {
  const abs = join(ROOT, path);
  const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
  if (current !== content) {
    stale.push(path);
    if (!CHECK) {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, content);
    }
  }
}
const extra = listOwned().filter((p) => !pages.has(p));
if (!CHECK) extra.forEach((p) => rmSync(join(ROOT, p)));
const navStale = docsJsonNext !== docsJsonRaw;
if (!CHECK && navStale) {
  writeFileSync(docsJsonPath, docsJsonNext);
  execFileSync(process.execPath, [join(ROOT, "scripts/check-routes.mjs"), "--write"], { stdio: "inherit" });
}

const counts = `${entries.length} MCP tools on ${MCP_GROUPS.length + 1} pages, ${ops.length} HTTP operations, ${gp.size} GDScript pages, ${pages.size} pages in all`;
if (problems.length) {
  console.error(`reference: FAIL\n  ${problems.join("\n  ")}`);
  process.exit(1);
}
if (CHECK) {
  if (stale.length || extra.length || navStale) {
    console.error("reference: FAIL generated reference is stale. Run `npm run generate:reference` and commit the result.");
    for (const p of stale) console.error(`  differs: ${p}`);
    for (const p of extra) console.error(`  not generated: ${p}`);
    if (navStale) console.error("  differs: docs.json (Reference tab)");
    process.exit(1);
  }
  console.log(`reference: PASS ${counts}`);
} else {
  console.log(`reference: wrote ${stale.length} pages, removed ${extra.length}${navStale ? ", updated docs.json" : ""}. ${counts}`);
}
