// Renders the Summer Platform HTTP API reference pages. Each operation is an
// MDX page whose `openapi:` frontmatter points Mintlify at the pinned public
// spec in scripts/reference/sources/openapi, so the URL comes from the
// operationId (stable) rather than from the summary text.

import { cell, code, escapeProse, firstSentence, fm, kebab } from "./lib/mdx.mjs";

export const HTTP_BASE = "api-reference/http";

/** The operation's summary, or its operationId in words ("listGameBuilds" -> "List game builds"). */
export function opTitle(op) {
  if (op.summary) return op.summary;
  const words = op.operationId.replace(/([a-z0-9])([A-Z])/g, "$1 $2").toLowerCase();
  return words.charAt(0).toUpperCase() + words.slice(1);
}
const METHODS = ["get", "put", "post", "patch", "delete"];

export function httpOperations(manifest, specs) {
  const out = [];
  for (const api of manifest.apis) {
    const spec = specs[api.id];
    for (const [path, item] of Object.entries(spec.paths)) {
      for (const method of METHODS) {
        const op = item[method];
        if (!op) continue;
        if (!op.operationId) throw new Error(`${api.id}: ${method.toUpperCase()} ${path} has no operationId`);
        out.push({
          api,
          method: method.toUpperCase(),
          path,
          op,
          tag: op.tags?.[0] ?? null,
          page: `${HTTP_BASE}/${api.id}/${kebab(op.operationId)}`,
          anonymous: Array.isArray(op.security) && op.security.length === 0,
        });
      }
    }
  }
  return out;
}

export function renderHttpOperationPage(o) {
  const title = opTitle(o.op);
  const desc = firstSentence(o.op.description || o.op.summary || `${o.method} ${o.path}`, 200);
  return [
    "---",
    `title: ${fm(title)}`,
    `description: ${fm(desc)}`,
    `openapi: ${fm(`/scripts/reference/sources/openapi/${o.api.id}.json ${o.method} ${o.path}`)}`,
    "generated: true",
    "generator: scripts/reference",
    "---",
    "",
    `{/* Generated by scripts/reference/generate.mjs from the public ${o.api.id} spec (summer-platform ${o.api.spec}). Do not edit by hand. */}`,
    "",
  ].join("\n");
}

export function renderHttpOverview(manifest, ops) {
  const lines = [
    "---",
    'title: "Summer Platform HTTP API"',
    'sidebarTitle: "Overview"',
    `description: ${fm("The public Summer Platform HTTP API: creator management, analytics reads, the Summer Games store and account basics. Base URL, sign-in and every operation, generated from the platform's OpenAPI specs.")}`,
    'icon: "globe"',
    "generated: true",
    "generator: scripts/reference",
    "---",
    "",
    `{/* Generated by scripts/reference/generate.mjs from scripts/reference/sources/http-api.json (summer-platform ${manifest.commit.slice(0, 10)}). Do not edit by hand. */}`,
    "",
    `All operations use one base URL: ${code(manifest.server)}. Most agents use these through the [MCP tools](/mcp/tools-reference) instead; call HTTP directly when you build your own tool or service.`,
    "",
    "<Note>",
    `Generated from the OpenAPI specs in summer-platform (${manifest.apis.map((a) => code(a.spec)).join(", ")}) at commit ${code(manifest.commit.slice(0, 10))}. Only operations that developers and agents can call from outside are listed; internal, staff, game-server and owner-only operations are left out. The allowlist is \`scripts/reference/http-api-allowlist.json\`.`,
    "</Note>",
    "",
  ];
  for (const api of manifest.apis) {
    const mine = ops.filter((o) => o.api.id === api.id);
    lines.push(`## ${api.title}`, "", escapeProse(api.description), "", `**Sign-in:** ${escapeProse(api.auth)}`, "", "| Operation | Method and path | Sign-in |", "|---|---|---|");
    for (const o of mine) {
      lines.push(`| [${cell(opTitle(o.op))}](/${o.page}) | ${code(`${o.method} ${o.path}`)} | ${o.anonymous ? "None" : "Bearer token"} |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** Navigation groups for docs.json: one per API, sub-grouped by tag. */
export function httpNav(manifest, ops) {
  return manifest.apis.map((api) => {
    const mine = ops.filter((o) => o.api.id === api.id);
    const tags = [...new Set(mine.map((o) => o.tag))];
    if (tags.length <= 1) return { group: api.title, pages: mine.map((o) => o.page) };
    return { group: api.title, pages: tags.map((t) => ({ group: t ?? "Other", pages: mine.filter((o) => o.tag === t).map((o) => o.page) })) };
  });
}
